# Definitions for config assertions. 
#
# Allows us to assert that config is as expected.
#
# The contents of this file are structured as follows:
#
# PLUGIN:
#   ASSERTION:
#     SETTINGS
#
# NOTE: this is currently only supported by the openstack plugin.
#
# See https://docs.python.org/3/library/operator.html for valid operator
# methods.
#
openstack:
  raises: core.issues.issue_types.OpenstackWarning
  nova-dpdk:
    config:
      handler: core.plugins.openstack.OpenstackConfig
      path: etc/nova/nova.conf
    requires:
      type: apt
      value: openvswitch-switch-dpdk
    message: >-
      DPDK is enabled but rx_queue_size/tx_queue_size set incorrectly in
      nova.conf (expect both to be >= 1024).
    settings:
      rx_queue_size:
        section: libvirt
        value: 1024
        operator: ge
        allow-unset: False
      tx_queue_size:
        section: libvirt
        value: 1024
        operator: ge
        allow-unset: False
storage:
  bcache:
    raises: core.issues.issue_types.BcacheWarning
    requires:
      type: property
      source: core.plugins.storage.bcache.BcacheBase.bcache_enabled
      value: True
    cset:
      config:
        handler: core.plugins.storage.bcache.CachesetsConfig
      settings:
        congested_read_threshold_us:
          value: 0
          operator: eq
        congested_write_threshold_us:
          value: 0
          operator: eq
    bdev:
      config:
        handler: core.plugins.storage.bcache.BdevsConfig
      settings:
        sequential_cutoff:
          value: '0.0k'
          operator: eq
        cache_mode:
          value: 'writethrough [writeback] writearound none'
          operator: eq
        writeback_percent:
          value: 10
          operator: ge
    lp1900438:
      config:
        handler: core.plugins.storage.bcache.CachesetsConfig
      message: >-
        bcache cache_available_percent approx. 30 which implies this node
        could be suffering from bug LP 1900438 - please check
      settings:
        # The real limit is 30 but we go just above in case bcache is flapping
        # just above and below the limit.
        cache_available_percent:
          value: 33
          operator: gt
  ceph:
    raises: core.issues.issue_types.CephWarning
    filestore-to-bluestore:
      message: >-
        bluestore is enabled yet there is a still a journal device
        configured in ceph.conf - please check
      requires:
        type: property
        source: core.plugins.storage.ceph.CephChecksBase.bluestore_enabled
        value: True
      config:
        handler: core.plugins.storage.ceph.CephConfig
      settings:
        osd_journal:
          value:
          operator: eq

