name: Pulls Sync
on:
  pull_request:
    types: opened
jobs:
  sync-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: 'Automation and Tooling'
          column: 'In Progress'
          repo-token: ${{ secrets.PROJ_MNG }}

